### ISSUE TITLE
超赞，已用于SmartSwipe的扩展库

### ISSUE THREAD

**Issue by luckybilly** [wuyr/ArrowDrawable#1]
@wuyr Hi, 小缘大佬
昨天在鸿洋公众号上看到这个动画，真心觉得很赞！
看到你将它制作成了SmartRefreshLayout的HeaderView，感觉效果很不错，就依赖[Ifxcyr/ArrowDrawable](https://github.com/Ifxcyr/ArrowDrawable)也为SmartSwipe的下拉刷新（一种SmartSwipe所封装的侧滑功能）制作了一个[ArrowHeader](https://github.com/luckybilly/SmartSwipe/blob/master/smart-swipe-refresh-ext/src/main/java/com/billy/android/swipe/ext/refresh/ArrowHeader.java)，发现也挺方便的！现已加入扩展包：smart-swipe-refresh-ext( [文档中相关的介绍](https://qibilly.com/SmartSwipe-tutorial/pages/SmartSwipeRefresh.html#扩展包：smart-swipe-refresh-ext))，并在多处注明了Based on [Ifxcyr/ArrowDrawable](https://github.com/Ifxcyr/ArrowDrawable)，**如有不妥之处，请告知我更改或者删除。**

demo效果图如下所示：
![refresh arrow](https://github.com/luckybilly/SmartSwipe/raw/master/images/refresh_arrow.gif)

[SmartSwipe](https://github.com/luckybilly/SmartSwipe/)是一个侧滑处理框架，不仅仅是某种特定的侧滑效果，而是对侧滑手势的一种封装，可以实现各种侧滑效果，其中[SmartSwipeRefresh](https://qibilly.com/SmartSwipe-tutorial/pages/SmartSwipeRefresh.html)是对下拉刷新功能的封装（`下拉上拉也是一种侧滑，不是吗？`）

**Comment by wuyr** [comment]
效果好棒\~d(*￣▽￣)===b     感谢支持\~ 接下来还有一个下拉刷新的动画效果呢。。。

**Comment by luckybilly** [comment]
期待~！

**Comment by wuyr** [comment]
同学你好！ 新的刷新动画已完成： [CoffeeDrawable](https://github.com/wuyr/CoffeeDrawable)
